linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  gosec:
    excludes:
      - G107
      - G401
      - G501
  staticcheck:
    go: "1.16"
    checks:
      - all
      - '-SA1019' # Disable: x509.DecryptPEMBlock has been deprecated
      - '-ST1018' # Disable: Unicode format character `U+` vs. `\u`
