linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  # gosec:
  #  excludes:
  #    - G107 # Url provided to HTTP request as taint input
  #    - G401 # Detect the usage of DES, RC4, MD5 or SHA1
  #    - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
  #    - G501 # Import blocklist: crypto/md5
  staticcheck:
    go: "1.16"
    checks:
      - all
    #  - '-SA1019' # Using a deprecated function, variable, constant or field: x509.DecryptPEMBlock has been deprecated
  stylecheck:
    go: "1.16"
    checks:
      - all
      - '-ST1018' # Avoid zero-width and control characters in string literals: Unicode format character `U+` vs. `\u`
