// timezone is a static list of timezones. It is incomplete as of now.
// Eventually it will be autogenerated using the approach as shown
// https://stackoverflow.com/questions/40120056/get-a-list-of-valid-time-zones-in-go
//
// https://stackoverflow.com/questions/61186388/user-friendly-time-zone-names-corresponding-to-iana-names
package timezone

const (
	TimezoneAmericaChicago    = "America/Chicago"
	TimezoneAmericaLosAngeles = "America/Los_Angeles"
)
