package languageutil

// ISO 639-1 language codes
const (
	Arabic     = "ar"
	Bangla     = "bn"
	Chinese    = "zh"
	Czech      = "cs"
	Danish     = "da"
	Dutch      = "nl"
	English    = "en"
	German     = "de"
	Greek      = "el"
	Spanish    = "es"
	Finnish    = "fi"
	French     = "fr"
	Hebrew     = "he"
	Hindi      = "hi"
	Hungarian  = "hu"
	Indonesian = "id"
	Italian    = "it"
	Japanese   = "jp"
	Korean     = "ko"
	Norwegian  = "no"
	Polish     = "pl"
	Portugese  = "pt"
	Romanian   = "ro"
	Russian    = "ru"
	Slovak     = "sk"
	Swedish    = "sv"
	Tamil      = "ta"
	Thai       = "th"
	Turkish    = "tr"
)
